version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    environment:
      - NEXT_PUBLIC_API_URL=https://smidra.com
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env.production    # Lägg till denna rad
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge 